#!/usr/bin/env bash
set -euo pipefail

# create-release-pr.sh — Update version, prepend changelog, create release PR.
# Usage: create-release-pr.sh <new-version> <changelog-section-file>

REPO="pacaplan/flokay"
PLUGIN_JSON=".claude-plugin/plugin.json"
MARKETPLACE_JSON=".claude-plugin/marketplace.json"
CHANGELOG="CHANGELOG.md"

NEW_VERSION="${1:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"
CHANGELOG_FILE="${2:?Usage: create-release-pr.sh <new-version> <changelog-section-file>}"

if [ ! -f "$CHANGELOG_FILE" ]; then
  echo "Error: changelog section file not found: $CHANGELOG_FILE" >&2
  exit 1
fi

# --- Update plugin.json version ---
jq --arg v "$NEW_VERSION" '.version = $v' "$PLUGIN_JSON" > "${PLUGIN_JSON}.tmp" \
  && mv "${PLUGIN_JSON}.tmp" "$PLUGIN_JSON"

# --- Update marketplace.json version ---
jq --arg v "$NEW_VERSION" '.plugins[0].version = $v' "$MARKETPLACE_JSON" > "${MARKETPLACE_JSON}.tmp" \
  && mv "${MARKETPLACE_JSON}.tmp" "$MARKETPLACE_JSON"

# --- Prepend changelog section ---
if [ -f "$CHANGELOG" ]; then
  # Insert new section after the "# flokay" header line
  {
    head -1 "$CHANGELOG"
    echo ""
    cat "$CHANGELOG_FILE"
    # Remaining lines after the header
    tail -n +2 "$CHANGELOG"
  } > "${CHANGELOG}.tmp" && mv "${CHANGELOG}.tmp" "$CHANGELOG"
else
  {
    echo "# flokay"
    echo ""
    cat "$CHANGELOG_FILE"
  } > "$CHANGELOG"
fi

# --- Create release branch ---
git checkout -B "release/v${NEW_VERSION}"

# --- Stage and commit ---
git add "$PLUGIN_JSON" "$MARKETPLACE_JSON" "$CHANGELOG"
git commit -m "chore: release v${NEW_VERSION}"

# --- Push and create PR ---
git push -u origin "release/v${NEW_VERSION}"

PR_URL=$(gh pr create --repo "$REPO" --base main \
  --title "chore: release v${NEW_VERSION}" \
  --body "$(cat <<EOF
## Release v${NEW_VERSION}

This PR was generated by the \`/release\` skill.
EOF
)")

echo "$PR_URL"
